menu:
  主页: /
  归档: /archives

logo: come back

more:
    #  友情链接: /links.html
  Github: https://github.com/zlj-zz/
  bilibili: https://space.bilibili.com/18175910
  微博: http://weibo.com/277008301
  知乎: https://www.zhihu.com/people/te-amo-88-81
  markdown 表格: https://tableconvert.com/
  #关于我: /

about:
  title: Theme Pln
  link: https://github.com/gaoryrt/hexo-theme-pln

show_toc: true

favicon:
    small: /images/favicon16.ico
    medium: /images/favicon32.ico

search:
  path: search.xml
  field: all

# If you want to use valine,you should get the appId and appKey form https://leancloud.cn ,more setting please see https://valine.js.org
valine:
  enable: false # !!if you want use valine comment system,please set enable: true
  appId: #your leancloud appId
  appKey: #your leancloud appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  avatar: mm # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn


excerpt_num: 120

footer_info: © zachary 2018-2020

latex: true
